// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: booking/booking.proto

package booking

import (
	common "booker/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueId       string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Table         *common.TableRef       `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Slot          *common.Slot           `protobuf:"bytes,4,opt,name=slot,proto3" json:"slot,omitempty"`
	PartySize     int32                  `protobuf:"varint,5,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	CustomerName  string                 `protobuf:"bytes,6,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,7,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // requested, held, confirmed, seated, finished, cancelled, expired, no_show, rejected
	Comment       string                 `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	AdminId       string                 `protobuf:"bytes,10,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // для held статуса
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *Booking) GetTable() *common.TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *Booking) GetSlot() *common.Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *Booking) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *Booking) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Booking) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Booking) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *Booking) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Booking) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Booking) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CreateBookingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VenueId        string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Table          *common.TableRef       `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Slot           *common.Slot           `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	PartySize      int32                  `protobuf:"varint,4,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	CustomerName   string                 `protobuf:"bytes,5,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerPhone  string                 `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Comment        string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	AdminId        string                 `protobuf:"bytes,8,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *CreateBookingRequest) GetTable() *common.TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *CreateBookingRequest) GetSlot() *common.Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *CreateBookingRequest) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *CreateBookingRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CreateBookingRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreateBookingRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateBookingRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *CreateBookingRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TableId       string                 `protobuf:"bytes,4,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_booking_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ListBookingsRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *ListBookingsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListBookingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBookingsRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *ListBookingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListBookingsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConfirmBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmBookingRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_booking_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{5}
}

func (x *CancelBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelBookingRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MarkSeatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkSeatedRequest) Reset() {
	*x = MarkSeatedRequest{}
	mi := &file_booking_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkSeatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkSeatedRequest) ProtoMessage() {}

func (x *MarkSeatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkSeatedRequest.ProtoReflect.Descriptor instead.
func (*MarkSeatedRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{6}
}

func (x *MarkSeatedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarkSeatedRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type MarkFinishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFinishedRequest) Reset() {
	*x = MarkFinishedRequest{}
	mi := &file_booking_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFinishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFinishedRequest) ProtoMessage() {}

func (x *MarkFinishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFinishedRequest.ProtoReflect.Descriptor instead.
func (*MarkFinishedRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{7}
}

func (x *MarkFinishedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarkFinishedRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type MarkNoShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNoShowRequest) Reset() {
	*x = MarkNoShowRequest{}
	mi := &file_booking_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNoShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNoShowRequest) ProtoMessage() {}

func (x *MarkNoShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNoShowRequest.ProtoReflect.Descriptor instead.
func (*MarkNoShowRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{8}
}

func (x *MarkNoShowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MarkNoShowRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_booking_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{9}
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListBookingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckTableAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	TableIds      []string               `protobuf:"bytes,2,rep,name=table_ids,json=tableIds,proto3" json:"table_ids,omitempty"`
	Slot          *common.Slot           `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTableAvailabilityRequest) Reset() {
	*x = CheckTableAvailabilityRequest{}
	mi := &file_booking_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTableAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTableAvailabilityRequest) ProtoMessage() {}

func (x *CheckTableAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTableAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckTableAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{10}
}

func (x *CheckTableAvailabilityRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *CheckTableAvailabilityRequest) GetTableIds() []string {
	if x != nil {
		return x.TableIds
	}
	return nil
}

func (x *CheckTableAvailabilityRequest) GetSlot() *common.Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

type CheckTableAvailabilityResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tables        []*TableAvailabilityInfo `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTableAvailabilityResponse) Reset() {
	*x = CheckTableAvailabilityResponse{}
	mi := &file_booking_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTableAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTableAvailabilityResponse) ProtoMessage() {}

func (x *CheckTableAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTableAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckTableAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{11}
}

func (x *CheckTableAvailabilityResponse) GetTables() []*TableAvailabilityInfo {
	if x != nil {
		return x.Tables
	}
	return nil
}

type TableAvailabilityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableAvailabilityInfo) Reset() {
	*x = TableAvailabilityInfo{}
	mi := &file_booking_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAvailabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAvailabilityInfo) ProtoMessage() {}

func (x *TableAvailabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_booking_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAvailabilityInfo.ProtoReflect.Descriptor instead.
func (*TableAvailabilityInfo) Descriptor() ([]byte, []int) {
	return file_booking_booking_proto_rawDescGZIP(), []int{12}
}

func (x *TableAvailabilityInfo) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TableAvailabilityInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *TableAvailabilityInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_booking_booking_proto protoreflect.FileDescriptor

const file_booking_booking_proto_rawDesc = "" +
	"\n" +
	"\x15booking/booking.proto\x12\abooking\x1a\x13common/events.proto\"\x93\x03\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12&\n" +
	"\x05table\x18\x03 \x01(\v2\x10.common.TableRefR\x05table\x12 \n" +
	"\x04slot\x18\x04 \x01(\v2\f.common.SlotR\x04slot\x12\x1d\n" +
	"\n" +
	"party_size\x18\x05 \x01(\x05R\tpartySize\x12#\n" +
	"\rcustomer_name\x18\x06 \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_phone\x18\a \x01(\tR\rcustomerPhone\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\acomment\x18\t \x01(\tR\acomment\x12\x19\n" +
	"\badmin_id\x18\n" +
	" \x01(\tR\aadminId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\r \x01(\x03R\texpiresAt\"\xc4\x02\n" +
	"\x14CreateBookingRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12&\n" +
	"\x05table\x18\x02 \x01(\v2\x10.common.TableRefR\x05table\x12 \n" +
	"\x04slot\x18\x03 \x01(\v2\f.common.SlotR\x04slot\x12\x1d\n" +
	"\n" +
	"party_size\x18\x04 \x01(\x05R\tpartySize\x12#\n" +
	"\rcustomer_name\x18\x05 \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_phone\x18\x06 \x01(\tR\rcustomerPhone\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x12\x19\n" +
	"\badmin_id\x18\b \x01(\tR\aadminId\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\"#\n" +
	"\x11GetBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa5\x01\n" +
	"\x13ListBookingsRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\btable_id\x18\x04 \x01(\tR\atableId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"B\n" +
	"\x15ConfirmBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\"Y\n" +
	"\x14CancelBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\">\n" +
	"\x11MarkSeatedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\"@\n" +
	"\x13MarkFinishedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\">\n" +
	"\x11MarkNoShowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\"Z\n" +
	"\x14ListBookingsResponse\x12,\n" +
	"\bbookings\x18\x01 \x03(\v2\x10.booking.BookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"y\n" +
	"\x1dCheckTableAvailabilityRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x1b\n" +
	"\ttable_ids\x18\x02 \x03(\tR\btableIds\x12 \n" +
	"\x04slot\x18\x03 \x01(\v2\f.common.SlotR\x04slot\"X\n" +
	"\x1eCheckTableAvailabilityResponse\x126\n" +
	"\x06tables\x18\x01 \x03(\v2\x1e.booking.TableAvailabilityInfoR\x06tables\"h\n" +
	"\x15TableAvailabilityInfo\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\x84\x05\n" +
	"\x0eBookingService\x12@\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x10.booking.Booking\x12K\n" +
	"\fListBookings\x12\x1c.booking.ListBookingsRequest\x1a\x1d.booking.ListBookingsResponse\x12B\n" +
	"\x0eConfirmBooking\x12\x1e.booking.ConfirmBookingRequest\x1a\x10.booking.Booking\x12@\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"MarkSeated\x12\x1a.booking.MarkSeatedRequest\x1a\x10.booking.Booking\x12>\n" +
	"\fMarkFinished\x12\x1c.booking.MarkFinishedRequest\x1a\x10.booking.Booking\x12:\n" +
	"\n" +
	"MarkNoShow\x12\x1a.booking.MarkNoShowRequest\x1a\x10.booking.Booking\x12i\n" +
	"\x16CheckTableAvailability\x12&.booking.CheckTableAvailabilityRequest\x1a'.booking.CheckTableAvailabilityResponseB\x1aZ\x18booker/pkg/proto/bookingb\x06proto3"

var (
	file_booking_booking_proto_rawDescOnce sync.Once
	file_booking_booking_proto_rawDescData []byte
)

func file_booking_booking_proto_rawDescGZIP() []byte {
	file_booking_booking_proto_rawDescOnce.Do(func() {
		file_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_booking_proto_rawDesc), len(file_booking_booking_proto_rawDesc)))
	})
	return file_booking_booking_proto_rawDescData
}

var file_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_booking_booking_proto_goTypes = []any{
	(*Booking)(nil),                        // 0: booking.Booking
	(*CreateBookingRequest)(nil),           // 1: booking.CreateBookingRequest
	(*GetBookingRequest)(nil),              // 2: booking.GetBookingRequest
	(*ListBookingsRequest)(nil),            // 3: booking.ListBookingsRequest
	(*ConfirmBookingRequest)(nil),          // 4: booking.ConfirmBookingRequest
	(*CancelBookingRequest)(nil),           // 5: booking.CancelBookingRequest
	(*MarkSeatedRequest)(nil),              // 6: booking.MarkSeatedRequest
	(*MarkFinishedRequest)(nil),            // 7: booking.MarkFinishedRequest
	(*MarkNoShowRequest)(nil),              // 8: booking.MarkNoShowRequest
	(*ListBookingsResponse)(nil),           // 9: booking.ListBookingsResponse
	(*CheckTableAvailabilityRequest)(nil),  // 10: booking.CheckTableAvailabilityRequest
	(*CheckTableAvailabilityResponse)(nil), // 11: booking.CheckTableAvailabilityResponse
	(*TableAvailabilityInfo)(nil),          // 12: booking.TableAvailabilityInfo
	(*common.TableRef)(nil),                // 13: common.TableRef
	(*common.Slot)(nil),                    // 14: common.Slot
}
var file_booking_booking_proto_depIdxs = []int32{
	13, // 0: booking.Booking.table:type_name -> common.TableRef
	14, // 1: booking.Booking.slot:type_name -> common.Slot
	13, // 2: booking.CreateBookingRequest.table:type_name -> common.TableRef
	14, // 3: booking.CreateBookingRequest.slot:type_name -> common.Slot
	0,  // 4: booking.ListBookingsResponse.bookings:type_name -> booking.Booking
	14, // 5: booking.CheckTableAvailabilityRequest.slot:type_name -> common.Slot
	12, // 6: booking.CheckTableAvailabilityResponse.tables:type_name -> booking.TableAvailabilityInfo
	1,  // 7: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	2,  // 8: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	3,  // 9: booking.BookingService.ListBookings:input_type -> booking.ListBookingsRequest
	4,  // 10: booking.BookingService.ConfirmBooking:input_type -> booking.ConfirmBookingRequest
	5,  // 11: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	6,  // 12: booking.BookingService.MarkSeated:input_type -> booking.MarkSeatedRequest
	7,  // 13: booking.BookingService.MarkFinished:input_type -> booking.MarkFinishedRequest
	8,  // 14: booking.BookingService.MarkNoShow:input_type -> booking.MarkNoShowRequest
	10, // 15: booking.BookingService.CheckTableAvailability:input_type -> booking.CheckTableAvailabilityRequest
	0,  // 16: booking.BookingService.CreateBooking:output_type -> booking.Booking
	0,  // 17: booking.BookingService.GetBooking:output_type -> booking.Booking
	9,  // 18: booking.BookingService.ListBookings:output_type -> booking.ListBookingsResponse
	0,  // 19: booking.BookingService.ConfirmBooking:output_type -> booking.Booking
	0,  // 20: booking.BookingService.CancelBooking:output_type -> booking.Booking
	0,  // 21: booking.BookingService.MarkSeated:output_type -> booking.Booking
	0,  // 22: booking.BookingService.MarkFinished:output_type -> booking.Booking
	0,  // 23: booking.BookingService.MarkNoShow:output_type -> booking.Booking
	11, // 24: booking.BookingService.CheckTableAvailability:output_type -> booking.CheckTableAvailabilityResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_booking_booking_proto_init() }
func file_booking_booking_proto_init() {
	if File_booking_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_booking_proto_rawDesc), len(file_booking_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_booking_proto_goTypes,
		DependencyIndexes: file_booking_booking_proto_depIdxs,
		MessageInfos:      file_booking_booking_proto_msgTypes,
	}.Build()
	File_booking_booking_proto = out.File
	file_booking_booking_proto_goTypes = nil
	file_booking_booking_proto_depIdxs = nil
}
