// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: common/events.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ссылка на стол
type TableRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRef) Reset() {
	*x = TableRef{}
	mi := &file_common_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRef) ProtoMessage() {}

func (x *TableRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRef.ProtoReflect.Descriptor instead.
func (*TableRef) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{0}
}

func (x *TableRef) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *TableRef) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableRef) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

// Временной слот
type Slot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                               // YYYY-MM-DD
	StartTime       string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                    // HH:MM
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // длительность в минутах
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_common_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Slot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Slot) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

// Заголовки события
type EventHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventHeaders) Reset() {
	*x = EventHeaders{}
	mi := &file_common_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHeaders) ProtoMessage() {}

func (x *EventHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHeaders.ProtoReflect.Descriptor instead.
func (*EventHeaders) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventHeaders) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventHeaders) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventHeaders) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// События бронирования
type BookingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       *EventHeaders          `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Table         *TableRef              `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Slot          *Slot                  `protobuf:"bytes,4,opt,name=slot,proto3" json:"slot,omitempty"`
	PartySize     int32                  `protobuf:"varint,5,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	CustomerName  string                 `protobuf:"bytes,6,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,7,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BookingEvent_Requested
	//	*BookingEvent_Held
	//	*BookingEvent_Confirmed
	//	*BookingEvent_Cancelled
	//	*BookingEvent_Expired
	//	*BookingEvent_Seated
	//	*BookingEvent_Finished
	//	*BookingEvent_NoShow
	//	*BookingEvent_Rejected
	Payload       isBookingEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingEvent) Reset() {
	*x = BookingEvent{}
	mi := &file_common_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingEvent) ProtoMessage() {}

func (x *BookingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingEvent.ProtoReflect.Descriptor instead.
func (*BookingEvent) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{3}
}

func (x *BookingEvent) GetHeaders() *EventHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *BookingEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *BookingEvent) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *BookingEvent) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *BookingEvent) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *BookingEvent) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *BookingEvent) GetPayload() isBookingEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BookingEvent) GetRequested() *BookingRequested {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Requested); ok {
			return x.Requested
		}
	}
	return nil
}

func (x *BookingEvent) GetHeld() *BookingHeld {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Held); ok {
			return x.Held
		}
	}
	return nil
}

func (x *BookingEvent) GetConfirmed() *BookingConfirmed {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Confirmed); ok {
			return x.Confirmed
		}
	}
	return nil
}

func (x *BookingEvent) GetCancelled() *BookingCancelled {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Cancelled); ok {
			return x.Cancelled
		}
	}
	return nil
}

func (x *BookingEvent) GetExpired() *BookingExpired {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Expired); ok {
			return x.Expired
		}
	}
	return nil
}

func (x *BookingEvent) GetSeated() *BookingSeated {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Seated); ok {
			return x.Seated
		}
	}
	return nil
}

func (x *BookingEvent) GetFinished() *BookingFinished {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

func (x *BookingEvent) GetNoShow() *BookingNoShow {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_NoShow); ok {
			return x.NoShow
		}
	}
	return nil
}

func (x *BookingEvent) GetRejected() *BookingRejected {
	if x != nil {
		if x, ok := x.Payload.(*BookingEvent_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isBookingEvent_Payload interface {
	isBookingEvent_Payload()
}

type BookingEvent_Requested struct {
	Requested *BookingRequested `protobuf:"bytes,10,opt,name=requested,proto3,oneof"`
}

type BookingEvent_Held struct {
	Held *BookingHeld `protobuf:"bytes,11,opt,name=held,proto3,oneof"`
}

type BookingEvent_Confirmed struct {
	Confirmed *BookingConfirmed `protobuf:"bytes,12,opt,name=confirmed,proto3,oneof"`
}

type BookingEvent_Cancelled struct {
	Cancelled *BookingCancelled `protobuf:"bytes,13,opt,name=cancelled,proto3,oneof"`
}

type BookingEvent_Expired struct {
	Expired *BookingExpired `protobuf:"bytes,14,opt,name=expired,proto3,oneof"`
}

type BookingEvent_Seated struct {
	Seated *BookingSeated `protobuf:"bytes,15,opt,name=seated,proto3,oneof"`
}

type BookingEvent_Finished struct {
	Finished *BookingFinished `protobuf:"bytes,16,opt,name=finished,proto3,oneof"`
}

type BookingEvent_NoShow struct {
	NoShow *BookingNoShow `protobuf:"bytes,17,opt,name=no_show,json=noShow,proto3,oneof"`
}

type BookingEvent_Rejected struct {
	Rejected *BookingRejected `protobuf:"bytes,18,opt,name=rejected,proto3,oneof"`
}

func (*BookingEvent_Requested) isBookingEvent_Payload() {}

func (*BookingEvent_Held) isBookingEvent_Payload() {}

func (*BookingEvent_Confirmed) isBookingEvent_Payload() {}

func (*BookingEvent_Cancelled) isBookingEvent_Payload() {}

func (*BookingEvent_Expired) isBookingEvent_Payload() {}

func (*BookingEvent_Seated) isBookingEvent_Payload() {}

func (*BookingEvent_Finished) isBookingEvent_Payload() {}

func (*BookingEvent_NoShow) isBookingEvent_Payload() {}

func (*BookingEvent_Rejected) isBookingEvent_Payload() {}

type BookingRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRequested) Reset() {
	*x = BookingRequested{}
	mi := &file_common_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequested) ProtoMessage() {}

func (x *BookingRequested) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequested.ProtoReflect.Descriptor instead.
func (*BookingRequested) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{4}
}

func (x *BookingRequested) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *BookingRequested) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type BookingHeld struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     int64                  `protobuf:"varint,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingHeld) Reset() {
	*x = BookingHeld{}
	mi := &file_common_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingHeld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingHeld) ProtoMessage() {}

func (x *BookingHeld) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingHeld.ProtoReflect.Descriptor instead.
func (*BookingHeld) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{5}
}

func (x *BookingHeld) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type BookingConfirmed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingConfirmed) Reset() {
	*x = BookingConfirmed{}
	mi := &file_common_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingConfirmed) ProtoMessage() {}

func (x *BookingConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingConfirmed.ProtoReflect.Descriptor instead.
func (*BookingConfirmed) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{6}
}

func (x *BookingConfirmed) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingCancelled) Reset() {
	*x = BookingCancelled{}
	mi := &file_common_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingCancelled) ProtoMessage() {}

func (x *BookingCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingCancelled.ProtoReflect.Descriptor instead.
func (*BookingCancelled) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{7}
}

func (x *BookingCancelled) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *BookingCancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BookingExpired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingExpired) Reset() {
	*x = BookingExpired{}
	mi := &file_common_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingExpired) ProtoMessage() {}

func (x *BookingExpired) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingExpired.ProtoReflect.Descriptor instead.
func (*BookingExpired) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{8}
}

func (x *BookingExpired) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BookingSeated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingSeated) Reset() {
	*x = BookingSeated{}
	mi := &file_common_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingSeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSeated) ProtoMessage() {}

func (x *BookingSeated) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSeated.ProtoReflect.Descriptor instead.
func (*BookingSeated) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{9}
}

func (x *BookingSeated) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingFinished) Reset() {
	*x = BookingFinished{}
	mi := &file_common_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingFinished) ProtoMessage() {}

func (x *BookingFinished) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingFinished.ProtoReflect.Descriptor instead.
func (*BookingFinished) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{10}
}

func (x *BookingFinished) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingNoShow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       string                 `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingNoShow) Reset() {
	*x = BookingNoShow{}
	mi := &file_common_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingNoShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingNoShow) ProtoMessage() {}

func (x *BookingNoShow) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingNoShow.ProtoReflect.Descriptor instead.
func (*BookingNoShow) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{11}
}

func (x *BookingNoShow) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRejected) Reset() {
	*x = BookingRejected{}
	mi := &file_common_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRejected) ProtoMessage() {}

func (x *BookingRejected) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRejected.ProtoReflect.Descriptor instead.
func (*BookingRejected) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{12}
}

func (x *BookingRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// События заведения
type VenueEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Headers *EventHeaders          `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	VenueId string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VenueEvent_LayoutUpdated
	//	*VenueEvent_ScheduleUpdated
	Payload       isVenueEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueEvent) Reset() {
	*x = VenueEvent{}
	mi := &file_common_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueEvent) ProtoMessage() {}

func (x *VenueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueEvent.ProtoReflect.Descriptor instead.
func (*VenueEvent) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{13}
}

func (x *VenueEvent) GetHeaders() *EventHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *VenueEvent) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *VenueEvent) GetPayload() isVenueEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VenueEvent) GetLayoutUpdated() *TableLayoutUpdated {
	if x != nil {
		if x, ok := x.Payload.(*VenueEvent_LayoutUpdated); ok {
			return x.LayoutUpdated
		}
	}
	return nil
}

func (x *VenueEvent) GetScheduleUpdated() *VenueScheduleUpdated {
	if x != nil {
		if x, ok := x.Payload.(*VenueEvent_ScheduleUpdated); ok {
			return x.ScheduleUpdated
		}
	}
	return nil
}

type isVenueEvent_Payload interface {
	isVenueEvent_Payload()
}

type VenueEvent_LayoutUpdated struct {
	LayoutUpdated *TableLayoutUpdated `protobuf:"bytes,10,opt,name=layout_updated,json=layoutUpdated,proto3,oneof"`
}

type VenueEvent_ScheduleUpdated struct {
	ScheduleUpdated *VenueScheduleUpdated `protobuf:"bytes,11,opt,name=schedule_updated,json=scheduleUpdated,proto3,oneof"`
}

func (*VenueEvent_LayoutUpdated) isVenueEvent_Payload() {}

func (*VenueEvent_ScheduleUpdated) isVenueEvent_Payload() {}

type TableLayoutUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableIds      []string               `protobuf:"bytes,2,rep,name=table_ids,json=tableIds,proto3" json:"table_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableLayoutUpdated) Reset() {
	*x = TableLayoutUpdated{}
	mi := &file_common_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableLayoutUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableLayoutUpdated) ProtoMessage() {}

func (x *TableLayoutUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableLayoutUpdated.ProtoReflect.Descriptor instead.
func (*TableLayoutUpdated) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{14}
}

func (x *TableLayoutUpdated) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableLayoutUpdated) GetTableIds() []string {
	if x != nil {
		return x.TableIds
	}
	return nil
}

type VenueScheduleUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD или пусто для всех
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VenueScheduleUpdated) Reset() {
	*x = VenueScheduleUpdated{}
	mi := &file_common_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VenueScheduleUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueScheduleUpdated) ProtoMessage() {}

func (x *VenueScheduleUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueScheduleUpdated.ProtoReflect.Descriptor instead.
func (*VenueScheduleUpdated) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{15}
}

func (x *VenueScheduleUpdated) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_common_events_proto protoreflect.FileDescriptor

const file_common_events_proto_rawDesc = "" +
	"\n" +
	"\x13common/events.proto\x12\x06common\"Y\n" +
	"\bTableRef\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"d\n" +
	"\x04Slot\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\"_\n" +
	"\fEventHeaders\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\xfb\x05\n" +
	"\fBookingEvent\x12.\n" +
	"\aheaders\x18\x01 \x01(\v2\x14.common.EventHeadersR\aheaders\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12&\n" +
	"\x05table\x18\x03 \x01(\v2\x10.common.TableRefR\x05table\x12 \n" +
	"\x04slot\x18\x04 \x01(\v2\f.common.SlotR\x04slot\x12\x1d\n" +
	"\n" +
	"party_size\x18\x05 \x01(\x05R\tpartySize\x12#\n" +
	"\rcustomer_name\x18\x06 \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_phone\x18\a \x01(\tR\rcustomerPhone\x128\n" +
	"\trequested\x18\n" +
	" \x01(\v2\x18.common.BookingRequestedH\x00R\trequested\x12)\n" +
	"\x04held\x18\v \x01(\v2\x13.common.BookingHeldH\x00R\x04held\x128\n" +
	"\tconfirmed\x18\f \x01(\v2\x18.common.BookingConfirmedH\x00R\tconfirmed\x128\n" +
	"\tcancelled\x18\r \x01(\v2\x18.common.BookingCancelledH\x00R\tcancelled\x122\n" +
	"\aexpired\x18\x0e \x01(\v2\x16.common.BookingExpiredH\x00R\aexpired\x12/\n" +
	"\x06seated\x18\x0f \x01(\v2\x15.common.BookingSeatedH\x00R\x06seated\x125\n" +
	"\bfinished\x18\x10 \x01(\v2\x17.common.BookingFinishedH\x00R\bfinished\x120\n" +
	"\ano_show\x18\x11 \x01(\v2\x15.common.BookingNoShowH\x00R\x06noShow\x125\n" +
	"\brejected\x18\x12 \x01(\v2\x17.common.BookingRejectedH\x00R\brejectedB\t\n" +
	"\apayload\"G\n" +
	"\x10BookingRequested\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\",\n" +
	"\vBookingHeld\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\x03R\texpiresAt\"-\n" +
	"\x10BookingConfirmed\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\"E\n" +
	"\x10BookingCancelled\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"(\n" +
	"\x0eBookingExpired\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"*\n" +
	"\rBookingSeated\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\",\n" +
	"\x0fBookingFinished\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\"*\n" +
	"\rBookingNoShow\x12\x19\n" +
	"\badmin_id\x18\x01 \x01(\tR\aadminId\")\n" +
	"\x0fBookingRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xf2\x01\n" +
	"\n" +
	"VenueEvent\x12.\n" +
	"\aheaders\x18\x01 \x01(\v2\x14.common.EventHeadersR\aheaders\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12C\n" +
	"\x0elayout_updated\x18\n" +
	" \x01(\v2\x1a.common.TableLayoutUpdatedH\x00R\rlayoutUpdated\x12I\n" +
	"\x10schedule_updated\x18\v \x01(\v2\x1c.common.VenueScheduleUpdatedH\x00R\x0fscheduleUpdatedB\t\n" +
	"\apayload\"J\n" +
	"\x12TableLayoutUpdated\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\ttable_ids\x18\x02 \x03(\tR\btableIds\"*\n" +
	"\x14VenueScheduleUpdated\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04dateB\x19Z\x17booker/pkg/proto/commonb\x06proto3"

var (
	file_common_events_proto_rawDescOnce sync.Once
	file_common_events_proto_rawDescData []byte
)

func file_common_events_proto_rawDescGZIP() []byte {
	file_common_events_proto_rawDescOnce.Do(func() {
		file_common_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_events_proto_rawDesc), len(file_common_events_proto_rawDesc)))
	})
	return file_common_events_proto_rawDescData
}

var file_common_events_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_common_events_proto_goTypes = []any{
	(*TableRef)(nil),             // 0: common.TableRef
	(*Slot)(nil),                 // 1: common.Slot
	(*EventHeaders)(nil),         // 2: common.EventHeaders
	(*BookingEvent)(nil),         // 3: common.BookingEvent
	(*BookingRequested)(nil),     // 4: common.BookingRequested
	(*BookingHeld)(nil),          // 5: common.BookingHeld
	(*BookingConfirmed)(nil),     // 6: common.BookingConfirmed
	(*BookingCancelled)(nil),     // 7: common.BookingCancelled
	(*BookingExpired)(nil),       // 8: common.BookingExpired
	(*BookingSeated)(nil),        // 9: common.BookingSeated
	(*BookingFinished)(nil),      // 10: common.BookingFinished
	(*BookingNoShow)(nil),        // 11: common.BookingNoShow
	(*BookingRejected)(nil),      // 12: common.BookingRejected
	(*VenueEvent)(nil),           // 13: common.VenueEvent
	(*TableLayoutUpdated)(nil),   // 14: common.TableLayoutUpdated
	(*VenueScheduleUpdated)(nil), // 15: common.VenueScheduleUpdated
}
var file_common_events_proto_depIdxs = []int32{
	2,  // 0: common.BookingEvent.headers:type_name -> common.EventHeaders
	0,  // 1: common.BookingEvent.table:type_name -> common.TableRef
	1,  // 2: common.BookingEvent.slot:type_name -> common.Slot
	4,  // 3: common.BookingEvent.requested:type_name -> common.BookingRequested
	5,  // 4: common.BookingEvent.held:type_name -> common.BookingHeld
	6,  // 5: common.BookingEvent.confirmed:type_name -> common.BookingConfirmed
	7,  // 6: common.BookingEvent.cancelled:type_name -> common.BookingCancelled
	8,  // 7: common.BookingEvent.expired:type_name -> common.BookingExpired
	9,  // 8: common.BookingEvent.seated:type_name -> common.BookingSeated
	10, // 9: common.BookingEvent.finished:type_name -> common.BookingFinished
	11, // 10: common.BookingEvent.no_show:type_name -> common.BookingNoShow
	12, // 11: common.BookingEvent.rejected:type_name -> common.BookingRejected
	2,  // 12: common.VenueEvent.headers:type_name -> common.EventHeaders
	14, // 13: common.VenueEvent.layout_updated:type_name -> common.TableLayoutUpdated
	15, // 14: common.VenueEvent.schedule_updated:type_name -> common.VenueScheduleUpdated
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_common_events_proto_init() }
func file_common_events_proto_init() {
	if File_common_events_proto != nil {
		return
	}
	file_common_events_proto_msgTypes[3].OneofWrappers = []any{
		(*BookingEvent_Requested)(nil),
		(*BookingEvent_Held)(nil),
		(*BookingEvent_Confirmed)(nil),
		(*BookingEvent_Cancelled)(nil),
		(*BookingEvent_Expired)(nil),
		(*BookingEvent_Seated)(nil),
		(*BookingEvent_Finished)(nil),
		(*BookingEvent_NoShow)(nil),
		(*BookingEvent_Rejected)(nil),
	}
	file_common_events_proto_msgTypes[13].OneofWrappers = []any{
		(*VenueEvent_LayoutUpdated)(nil),
		(*VenueEvent_ScheduleUpdated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_events_proto_rawDesc), len(file_common_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_events_proto_goTypes,
		DependencyIndexes: file_common_events_proto_depIdxs,
		MessageInfos:      file_common_events_proto_msgTypes,
	}.Build()
	File_common_events_proto = out.File
	file_common_events_proto_goTypes = nil
	file_common_events_proto_depIdxs = nil
}
