// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: common/events.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ссылка на стол
type TableRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	RoomId  string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *TableRef) Reset() {
	*x = TableRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRef) ProtoMessage() {}

func (x *TableRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRef.ProtoReflect.Descriptor instead.
func (*TableRef) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{0}
}

func (x *TableRef) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *TableRef) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableRef) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

// Временной слот
type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date            string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                               // YYYY-MM-DD
	StartTime       string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                    // HH:MM
	DurationMinutes int32  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // длительность в минутах
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Slot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Slot) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

// Заголовки события
type EventHeaders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId   string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source    string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *EventHeaders) Reset() {
	*x = EventHeaders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHeaders) ProtoMessage() {}

func (x *EventHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHeaders.ProtoReflect.Descriptor instead.
func (*EventHeaders) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventHeaders) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventHeaders) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EventHeaders) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// События бронирования
type BookingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers       *EventHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	BookingId     string        `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Table         *TableRef     `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Slot          *Slot         `protobuf:"bytes,4,opt,name=slot,proto3" json:"slot,omitempty"`
	PartySize     int32         `protobuf:"varint,5,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	CustomerName  string        `protobuf:"bytes,6,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerPhone string        `protobuf:"bytes,7,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*BookingEvent_Requested
	//	*BookingEvent_Held
	//	*BookingEvent_Confirmed
	//	*BookingEvent_Cancelled
	//	*BookingEvent_Expired
	//	*BookingEvent_Seated
	//	*BookingEvent_Finished
	//	*BookingEvent_NoShow
	//	*BookingEvent_Rejected
	Payload isBookingEvent_Payload `protobuf_oneof:"payload"`
}

func (x *BookingEvent) Reset() {
	*x = BookingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingEvent) ProtoMessage() {}

func (x *BookingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingEvent.ProtoReflect.Descriptor instead.
func (*BookingEvent) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{3}
}

func (x *BookingEvent) GetHeaders() *EventHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *BookingEvent) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingEvent) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *BookingEvent) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *BookingEvent) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

func (x *BookingEvent) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *BookingEvent) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (m *BookingEvent) GetPayload() isBookingEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *BookingEvent) GetRequested() *BookingRequested {
	if x, ok := x.GetPayload().(*BookingEvent_Requested); ok {
		return x.Requested
	}
	return nil
}

func (x *BookingEvent) GetHeld() *BookingHeld {
	if x, ok := x.GetPayload().(*BookingEvent_Held); ok {
		return x.Held
	}
	return nil
}

func (x *BookingEvent) GetConfirmed() *BookingConfirmed {
	if x, ok := x.GetPayload().(*BookingEvent_Confirmed); ok {
		return x.Confirmed
	}
	return nil
}

func (x *BookingEvent) GetCancelled() *BookingCancelled {
	if x, ok := x.GetPayload().(*BookingEvent_Cancelled); ok {
		return x.Cancelled
	}
	return nil
}

func (x *BookingEvent) GetExpired() *BookingExpired {
	if x, ok := x.GetPayload().(*BookingEvent_Expired); ok {
		return x.Expired
	}
	return nil
}

func (x *BookingEvent) GetSeated() *BookingSeated {
	if x, ok := x.GetPayload().(*BookingEvent_Seated); ok {
		return x.Seated
	}
	return nil
}

func (x *BookingEvent) GetFinished() *BookingFinished {
	if x, ok := x.GetPayload().(*BookingEvent_Finished); ok {
		return x.Finished
	}
	return nil
}

func (x *BookingEvent) GetNoShow() *BookingNoShow {
	if x, ok := x.GetPayload().(*BookingEvent_NoShow); ok {
		return x.NoShow
	}
	return nil
}

func (x *BookingEvent) GetRejected() *BookingRejected {
	if x, ok := x.GetPayload().(*BookingEvent_Rejected); ok {
		return x.Rejected
	}
	return nil
}

type isBookingEvent_Payload interface {
	isBookingEvent_Payload()
}

type BookingEvent_Requested struct {
	Requested *BookingRequested `protobuf:"bytes,10,opt,name=requested,proto3,oneof"`
}

type BookingEvent_Held struct {
	Held *BookingHeld `protobuf:"bytes,11,opt,name=held,proto3,oneof"`
}

type BookingEvent_Confirmed struct {
	Confirmed *BookingConfirmed `protobuf:"bytes,12,opt,name=confirmed,proto3,oneof"`
}

type BookingEvent_Cancelled struct {
	Cancelled *BookingCancelled `protobuf:"bytes,13,opt,name=cancelled,proto3,oneof"`
}

type BookingEvent_Expired struct {
	Expired *BookingExpired `protobuf:"bytes,14,opt,name=expired,proto3,oneof"`
}

type BookingEvent_Seated struct {
	Seated *BookingSeated `protobuf:"bytes,15,opt,name=seated,proto3,oneof"`
}

type BookingEvent_Finished struct {
	Finished *BookingFinished `protobuf:"bytes,16,opt,name=finished,proto3,oneof"`
}

type BookingEvent_NoShow struct {
	NoShow *BookingNoShow `protobuf:"bytes,17,opt,name=no_show,json=noShow,proto3,oneof"`
}

type BookingEvent_Rejected struct {
	Rejected *BookingRejected `protobuf:"bytes,18,opt,name=rejected,proto3,oneof"`
}

func (*BookingEvent_Requested) isBookingEvent_Payload() {}

func (*BookingEvent_Held) isBookingEvent_Payload() {}

func (*BookingEvent_Confirmed) isBookingEvent_Payload() {}

func (*BookingEvent_Cancelled) isBookingEvent_Payload() {}

func (*BookingEvent_Expired) isBookingEvent_Payload() {}

func (*BookingEvent_Seated) isBookingEvent_Payload() {}

func (*BookingEvent_Finished) isBookingEvent_Payload() {}

func (*BookingEvent_NoShow) isBookingEvent_Payload() {}

func (*BookingEvent_Rejected) isBookingEvent_Payload() {}

type BookingRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *BookingRequested) Reset() {
	*x = BookingRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRequested) ProtoMessage() {}

func (x *BookingRequested) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRequested.ProtoReflect.Descriptor instead.
func (*BookingRequested) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{4}
}

func (x *BookingRequested) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *BookingRequested) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type BookingHeld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpiresAt int64 `protobuf:"varint,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
}

func (x *BookingHeld) Reset() {
	*x = BookingHeld{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingHeld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingHeld) ProtoMessage() {}

func (x *BookingHeld) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingHeld.ProtoReflect.Descriptor instead.
func (*BookingHeld) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{5}
}

func (x *BookingHeld) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type BookingConfirmed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
}

func (x *BookingConfirmed) Reset() {
	*x = BookingConfirmed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingConfirmed) ProtoMessage() {}

func (x *BookingConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingConfirmed.ProtoReflect.Descriptor instead.
func (*BookingConfirmed) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{6}
}

func (x *BookingConfirmed) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BookingCancelled) Reset() {
	*x = BookingCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingCancelled) ProtoMessage() {}

func (x *BookingCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingCancelled.ProtoReflect.Descriptor instead.
func (*BookingCancelled) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{7}
}

func (x *BookingCancelled) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *BookingCancelled) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BookingExpired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BookingExpired) Reset() {
	*x = BookingExpired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingExpired) ProtoMessage() {}

func (x *BookingExpired) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingExpired.ProtoReflect.Descriptor instead.
func (*BookingExpired) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{8}
}

func (x *BookingExpired) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BookingSeated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
}

func (x *BookingSeated) Reset() {
	*x = BookingSeated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingSeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSeated) ProtoMessage() {}

func (x *BookingSeated) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSeated.ProtoReflect.Descriptor instead.
func (*BookingSeated) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{9}
}

func (x *BookingSeated) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
}

func (x *BookingFinished) Reset() {
	*x = BookingFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingFinished) ProtoMessage() {}

func (x *BookingFinished) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingFinished.ProtoReflect.Descriptor instead.
func (*BookingFinished) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{10}
}

func (x *BookingFinished) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingNoShow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId string `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
}

func (x *BookingNoShow) Reset() {
	*x = BookingNoShow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingNoShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingNoShow) ProtoMessage() {}

func (x *BookingNoShow) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingNoShow.ProtoReflect.Descriptor instead.
func (*BookingNoShow) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{11}
}

func (x *BookingNoShow) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BookingRejected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BookingRejected) Reset() {
	*x = BookingRejected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookingRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRejected) ProtoMessage() {}

func (x *BookingRejected) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRejected.ProtoReflect.Descriptor instead.
func (*BookingRejected) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{12}
}

func (x *BookingRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// События заведения
type VenueEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers *EventHeaders `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	VenueId string        `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*VenueEvent_LayoutUpdated
	//	*VenueEvent_ScheduleUpdated
	Payload isVenueEvent_Payload `protobuf_oneof:"payload"`
}

func (x *VenueEvent) Reset() {
	*x = VenueEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VenueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueEvent) ProtoMessage() {}

func (x *VenueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueEvent.ProtoReflect.Descriptor instead.
func (*VenueEvent) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{13}
}

func (x *VenueEvent) GetHeaders() *EventHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *VenueEvent) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (m *VenueEvent) GetPayload() isVenueEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *VenueEvent) GetLayoutUpdated() *TableLayoutUpdated {
	if x, ok := x.GetPayload().(*VenueEvent_LayoutUpdated); ok {
		return x.LayoutUpdated
	}
	return nil
}

func (x *VenueEvent) GetScheduleUpdated() *VenueScheduleUpdated {
	if x, ok := x.GetPayload().(*VenueEvent_ScheduleUpdated); ok {
		return x.ScheduleUpdated
	}
	return nil
}

type isVenueEvent_Payload interface {
	isVenueEvent_Payload()
}

type VenueEvent_LayoutUpdated struct {
	LayoutUpdated *TableLayoutUpdated `protobuf:"bytes,10,opt,name=layout_updated,json=layoutUpdated,proto3,oneof"`
}

type VenueEvent_ScheduleUpdated struct {
	ScheduleUpdated *VenueScheduleUpdated `protobuf:"bytes,11,opt,name=schedule_updated,json=scheduleUpdated,proto3,oneof"`
}

func (*VenueEvent_LayoutUpdated) isVenueEvent_Payload() {}

func (*VenueEvent_ScheduleUpdated) isVenueEvent_Payload() {}

type TableLayoutUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TableIds []string `protobuf:"bytes,2,rep,name=table_ids,json=tableIds,proto3" json:"table_ids,omitempty"`
}

func (x *TableLayoutUpdated) Reset() {
	*x = TableLayoutUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableLayoutUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableLayoutUpdated) ProtoMessage() {}

func (x *TableLayoutUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableLayoutUpdated.ProtoReflect.Descriptor instead.
func (*TableLayoutUpdated) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{14}
}

func (x *TableLayoutUpdated) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *TableLayoutUpdated) GetTableIds() []string {
	if x != nil {
		return x.TableIds
	}
	return nil
}

type VenueScheduleUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD или пусто для всех
}

func (x *VenueScheduleUpdated) Reset() {
	*x = VenueScheduleUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_events_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VenueScheduleUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VenueScheduleUpdated) ProtoMessage() {}

func (x *VenueScheduleUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_common_events_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VenueScheduleUpdated.ProtoReflect.Descriptor instead.
func (*VenueScheduleUpdated) Descriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{15}
}

func (x *VenueScheduleUpdated) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_common_events_proto protoreflect.FileDescriptor

var file_common_events_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x59, 0x0a,
	0x08, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x66, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x22, 0x5f,
	0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22,
	0xfb, 0x05, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x2e, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x66,
	0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53,
	0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72,
	0x74, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x29,
	0x0a, 0x04, 0x68, 0x65, 0x6c, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x6c,
	0x64, 0x48, 0x00, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x32, 0x0a,
	0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x07, 0x6e, 0x6f, 0x5f,
	0x73, 0x68, 0x6f, 0x77, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x53, 0x68, 0x6f,
	0x77, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x6f, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x35, 0x0a, 0x08, 0x72,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x47, 0x0a,
	0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x48, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73,
	0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x22, 0x2d, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x28, 0x0a, 0x0e, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64,
	0x22, 0x2c, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x2a,
	0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x53, 0x68, 0x6f, 0x77, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xf2, 0x01, 0x0a, 0x0a, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x07, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x12,
	0x43, 0x0a, 0x0e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x49, 0x0a, 0x10, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0f,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4a, 0x0a, 0x12, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x22, 0x2a, 0x0a, 0x14, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_events_proto_rawDescOnce sync.Once
	file_common_events_proto_rawDescData = file_common_events_proto_rawDesc
)

func file_common_events_proto_rawDescGZIP() []byte {
	file_common_events_proto_rawDescOnce.Do(func() {
		file_common_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_events_proto_rawDescData)
	})
	return file_common_events_proto_rawDescData
}

var file_common_events_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_common_events_proto_goTypes = []interface{}{
	(*TableRef)(nil),             // 0: common.TableRef
	(*Slot)(nil),                 // 1: common.Slot
	(*EventHeaders)(nil),         // 2: common.EventHeaders
	(*BookingEvent)(nil),         // 3: common.BookingEvent
	(*BookingRequested)(nil),     // 4: common.BookingRequested
	(*BookingHeld)(nil),          // 5: common.BookingHeld
	(*BookingConfirmed)(nil),     // 6: common.BookingConfirmed
	(*BookingCancelled)(nil),     // 7: common.BookingCancelled
	(*BookingExpired)(nil),       // 8: common.BookingExpired
	(*BookingSeated)(nil),        // 9: common.BookingSeated
	(*BookingFinished)(nil),      // 10: common.BookingFinished
	(*BookingNoShow)(nil),        // 11: common.BookingNoShow
	(*BookingRejected)(nil),      // 12: common.BookingRejected
	(*VenueEvent)(nil),           // 13: common.VenueEvent
	(*TableLayoutUpdated)(nil),   // 14: common.TableLayoutUpdated
	(*VenueScheduleUpdated)(nil), // 15: common.VenueScheduleUpdated
}
var file_common_events_proto_depIdxs = []int32{
	2,  // 0: common.BookingEvent.headers:type_name -> common.EventHeaders
	0,  // 1: common.BookingEvent.table:type_name -> common.TableRef
	1,  // 2: common.BookingEvent.slot:type_name -> common.Slot
	4,  // 3: common.BookingEvent.requested:type_name -> common.BookingRequested
	5,  // 4: common.BookingEvent.held:type_name -> common.BookingHeld
	6,  // 5: common.BookingEvent.confirmed:type_name -> common.BookingConfirmed
	7,  // 6: common.BookingEvent.cancelled:type_name -> common.BookingCancelled
	8,  // 7: common.BookingEvent.expired:type_name -> common.BookingExpired
	9,  // 8: common.BookingEvent.seated:type_name -> common.BookingSeated
	10, // 9: common.BookingEvent.finished:type_name -> common.BookingFinished
	11, // 10: common.BookingEvent.no_show:type_name -> common.BookingNoShow
	12, // 11: common.BookingEvent.rejected:type_name -> common.BookingRejected
	2,  // 12: common.VenueEvent.headers:type_name -> common.EventHeaders
	14, // 13: common.VenueEvent.layout_updated:type_name -> common.TableLayoutUpdated
	15, // 14: common.VenueEvent.schedule_updated:type_name -> common.VenueScheduleUpdated
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_common_events_proto_init() }
func file_common_events_proto_init() {
	if File_common_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventHeaders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingHeld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingConfirmed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingExpired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingSeated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingNoShow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookingRejected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VenueEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableLayoutUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_events_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VenueScheduleUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_events_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*BookingEvent_Requested)(nil),
		(*BookingEvent_Held)(nil),
		(*BookingEvent_Confirmed)(nil),
		(*BookingEvent_Cancelled)(nil),
		(*BookingEvent_Expired)(nil),
		(*BookingEvent_Seated)(nil),
		(*BookingEvent_Finished)(nil),
		(*BookingEvent_NoShow)(nil),
		(*BookingEvent_Rejected)(nil),
	}
	file_common_events_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*VenueEvent_LayoutUpdated)(nil),
		(*VenueEvent_ScheduleUpdated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_events_proto_goTypes,
		DependencyIndexes: file_common_events_proto_depIdxs,
		MessageInfos:      file_common_events_proto_msgTypes,
	}.Build()
	File_common_events_proto = out.File
	file_common_events_proto_rawDesc = nil
	file_common_events_proto_goTypes = nil
	file_common_events_proto_depIdxs = nil
}
