// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: venue/venue.proto

package venue

import (
	common "booker/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Venue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Venue) Reset() {
	*x = Venue{}
	mi := &file_venue_venue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Venue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue) ProtoMessage() {}

func (x *Venue) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue.ProtoReflect.Descriptor instead.
func (*Venue) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{0}
}

func (x *Venue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Venue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Venue) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Venue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Venue) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Venue) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueId       string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_venue_venue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Room) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CanMerge      bool                   `protobuf:"varint,5,opt,name=can_merge,json=canMerge,proto3" json:"can_merge,omitempty"`
	Zone          string                 `protobuf:"bytes,6,opt,name=zone,proto3" json:"zone,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_venue_venue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Table) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Table) GetCanMerge() bool {
	if x != nil {
		return x.CanMerge
	}
	return false
}

func (x *Table) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Table) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Table) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type OpeningHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Days          []*DayHours            `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpeningHours) Reset() {
	*x = OpeningHours{}
	mi := &file_venue_venue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpeningHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningHours) ProtoMessage() {}

func (x *OpeningHours) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningHours.ProtoReflect.Descriptor instead.
func (*OpeningHours) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{3}
}

func (x *OpeningHours) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *OpeningHours) GetDays() []*DayHours {
	if x != nil {
		return x.Days
	}
	return nil
}

type DayHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weekday       int32                  `protobuf:"varint,1,opt,name=weekday,proto3" json:"weekday,omitempty"`                     // 0-6, 0=Sunday
	OpenTime      string                 `protobuf:"bytes,2,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`    // HH:MM
	CloseTime     string                 `protobuf:"bytes,3,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"` // HH:MM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayHours) Reset() {
	*x = DayHours{}
	mi := &file_venue_venue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayHours) ProtoMessage() {}

func (x *DayHours) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayHours.ProtoReflect.Descriptor instead.
func (*DayHours) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{4}
}

func (x *DayHours) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *DayHours) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *DayHours) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

type SpecialHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	OpenTime      string                 `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	IsClosed      bool                   `protobuf:"varint,5,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialHours) Reset() {
	*x = SpecialHours{}
	mi := &file_venue_venue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialHours) ProtoMessage() {}

func (x *SpecialHours) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialHours.ProtoReflect.Descriptor instead.
func (*SpecialHours) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{5}
}

func (x *SpecialHours) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *SpecialHours) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SpecialHours) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *SpecialHours) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *SpecialHours) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

// Requests
type CreateVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVenueRequest) Reset() {
	*x = CreateVenueRequest{}
	mi := &file_venue_venue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVenueRequest) ProtoMessage() {}

func (x *CreateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVenueRequest.ProtoReflect.Descriptor instead.
func (*CreateVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVenueRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateVenueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVenueRequest) Reset() {
	*x = GetVenueRequest{}
	mi := &file_venue_venue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVenueRequest) ProtoMessage() {}

func (x *GetVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVenueRequest.ProtoReflect.Descriptor instead.
func (*GetVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{7}
}

func (x *GetVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListVenuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesRequest) Reset() {
	*x = ListVenuesRequest{}
	mi := &file_venue_venue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesRequest) ProtoMessage() {}

func (x *ListVenuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesRequest.ProtoReflect.Descriptor instead.
func (*ListVenuesRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{8}
}

func (x *ListVenuesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVenuesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVenueRequest) Reset() {
	*x = UpdateVenueRequest{}
	mi := &file_venue_venue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVenueRequest) ProtoMessage() {}

func (x *UpdateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVenueRequest.ProtoReflect.Descriptor instead.
func (*UpdateVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVenueRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeleteVenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVenueRequest) Reset() {
	*x = DeleteVenueRequest{}
	mi := &file_venue_venue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVenueRequest) ProtoMessage() {}

func (x *DeleteVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVenueRequest.ProtoReflect.Descriptor instead.
func (*DeleteVenueRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_venue_venue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRoomRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_venue_venue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_venue_venue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{13}
}

func (x *ListRoomsRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *ListRoomsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoomsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_venue_venue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_venue_venue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CanMerge      bool                   `protobuf:"varint,4,opt,name=can_merge,json=canMerge,proto3" json:"can_merge,omitempty"`
	Zone          string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableRequest) Reset() {
	*x = CreateTableRequest{}
	mi := &file_venue_venue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRequest) ProtoMessage() {}

func (x *CreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRequest.ProtoReflect.Descriptor instead.
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{16}
}

func (x *CreateTableRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateTableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTableRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateTableRequest) GetCanMerge() bool {
	if x != nil {
		return x.CanMerge
	}
	return false
}

func (x *CreateTableRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type GetTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableRequest) Reset() {
	*x = GetTableRequest{}
	mi := &file_venue_venue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableRequest) ProtoMessage() {}

func (x *GetTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableRequest.ProtoReflect.Descriptor instead.
func (*GetTableRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{17}
}

func (x *GetTableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	VenueId       string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesRequest) Reset() {
	*x = ListTablesRequest{}
	mi := &file_venue_venue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesRequest) ProtoMessage() {}

func (x *ListTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesRequest.ProtoReflect.Descriptor instead.
func (*ListTablesRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{18}
}

func (x *ListTablesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListTablesRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *ListTablesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTablesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTableRequest) Reset() {
	*x = UpdateTableRequest{}
	mi := &file_venue_venue_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTableRequest) ProtoMessage() {}

func (x *UpdateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTableRequest.ProtoReflect.Descriptor instead.
func (*UpdateTableRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateTableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTableRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateTableRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type DeleteTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTableRequest) Reset() {
	*x = DeleteTableRequest{}
	mi := &file_venue_venue_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTableRequest) ProtoMessage() {}

func (x *DeleteTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTableRequest.ProtoReflect.Descriptor instead.
func (*DeleteTableRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteTableRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetOpeningHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Days          []*DayHours            `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOpeningHoursRequest) Reset() {
	*x = SetOpeningHoursRequest{}
	mi := &file_venue_venue_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOpeningHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOpeningHoursRequest) ProtoMessage() {}

func (x *SetOpeningHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOpeningHoursRequest.ProtoReflect.Descriptor instead.
func (*SetOpeningHoursRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{21}
}

func (x *SetOpeningHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *SetOpeningHoursRequest) GetDays() []*DayHours {
	if x != nil {
		return x.Days
	}
	return nil
}

type GetOpeningHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpeningHoursRequest) Reset() {
	*x = GetOpeningHoursRequest{}
	mi := &file_venue_venue_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpeningHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpeningHoursRequest) ProtoMessage() {}

func (x *GetOpeningHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpeningHoursRequest.ProtoReflect.Descriptor instead.
func (*GetOpeningHoursRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{22}
}

func (x *GetOpeningHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type SetSpecialHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	OpenTime      string                 `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	IsClosed      bool                   `protobuf:"varint,5,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpecialHoursRequest) Reset() {
	*x = SetSpecialHoursRequest{}
	mi := &file_venue_venue_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpecialHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpecialHoursRequest) ProtoMessage() {}

func (x *SetSpecialHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpecialHoursRequest.ProtoReflect.Descriptor instead.
func (*SetSpecialHoursRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{23}
}

func (x *SetSpecialHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *SetSpecialHoursRequest) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Slot          *common.Slot           `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	PartySize     int32                  `protobuf:"varint,3,opt,name=party_size,json=partySize,proto3" json:"party_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_venue_venue_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{24}
}

func (x *CheckAvailabilityRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetSlot() *common.Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *CheckAvailabilityRequest) GetPartySize() int32 {
	if x != nil {
		return x.PartySize
	}
	return 0
}

type CheckAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableAvailability   `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_venue_venue_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{25}
}

func (x *CheckAvailabilityResponse) GetTables() []*TableAvailability {
	if x != nil {
		return x.Tables
	}
	return nil
}

type TableAvailability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Table           *common.TableRef       `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Available       bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	MergedWithTable *common.TableRef       `protobuf:"bytes,4,opt,name=merged_with_table,json=mergedWithTable,proto3" json:"merged_with_table,omitempty"` // If this table can be merged with another table
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TableAvailability) Reset() {
	*x = TableAvailability{}
	mi := &file_venue_venue_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableAvailability) ProtoMessage() {}

func (x *TableAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableAvailability.ProtoReflect.Descriptor instead.
func (*TableAvailability) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{26}
}

func (x *TableAvailability) GetTable() *common.TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *TableAvailability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *TableAvailability) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TableAvailability) GetMergedWithTable() *common.TableRef {
	if x != nil {
		return x.MergedWithTable
	}
	return nil
}

type GetTableLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VenueId       string                 `protobuf:"bytes,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableLayoutRequest) Reset() {
	*x = GetTableLayoutRequest{}
	mi := &file_venue_venue_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableLayoutRequest) ProtoMessage() {}

func (x *GetTableLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableLayoutRequest.ProtoReflect.Descriptor instead.
func (*GetTableLayoutRequest) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{27}
}

func (x *GetTableLayoutRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *GetTableLayoutRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetTableLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Tables        []*Table               `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableLayoutResponse) Reset() {
	*x = GetTableLayoutResponse{}
	mi := &file_venue_venue_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableLayoutResponse) ProtoMessage() {}

func (x *GetTableLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableLayoutResponse.ProtoReflect.Descriptor instead.
func (*GetTableLayoutResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{28}
}

func (x *GetTableLayoutResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetTableLayoutResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

// Responses
type ListVenuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venues        []*Venue               `protobuf:"bytes,1,rep,name=venues,proto3" json:"venues,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesResponse) Reset() {
	*x = ListVenuesResponse{}
	mi := &file_venue_venue_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesResponse) ProtoMessage() {}

func (x *ListVenuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesResponse.ProtoReflect.Descriptor instead.
func (*ListVenuesResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{29}
}

func (x *ListVenuesResponse) GetVenues() []*Venue {
	if x != nil {
		return x.Venues
	}
	return nil
}

func (x *ListVenuesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_venue_venue_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{30}
}

func (x *ListRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListRoomsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*Table               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesResponse) Reset() {
	*x = ListTablesResponse{}
	mi := &file_venue_venue_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesResponse) ProtoMessage() {}

func (x *ListTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesResponse.ProtoReflect.Descriptor instead.
func (*ListTablesResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{31}
}

func (x *ListTablesResponse) GetTables() []*Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *ListTablesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetOpeningHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOpeningHoursResponse) Reset() {
	*x = SetOpeningHoursResponse{}
	mi := &file_venue_venue_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOpeningHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOpeningHoursResponse) ProtoMessage() {}

func (x *SetOpeningHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOpeningHoursResponse.ProtoReflect.Descriptor instead.
func (*SetOpeningHoursResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{32}
}

func (x *SetOpeningHoursResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteVenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVenueResponse) Reset() {
	*x = DeleteVenueResponse{}
	mi := &file_venue_venue_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVenueResponse) ProtoMessage() {}

func (x *DeleteVenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVenueResponse.ProtoReflect.Descriptor instead.
func (*DeleteVenueResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteVenueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_venue_venue_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTableResponse) Reset() {
	*x = DeleteTableResponse{}
	mi := &file_venue_venue_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTableResponse) ProtoMessage() {}

func (x *DeleteTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTableResponse.ProtoReflect.Descriptor instead.
func (*DeleteTableResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetSpecialHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSpecialHoursResponse) Reset() {
	*x = SetSpecialHoursResponse{}
	mi := &file_venue_venue_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSpecialHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpecialHoursResponse) ProtoMessage() {}

func (x *SetSpecialHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_venue_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpecialHoursResponse.ProtoReflect.Descriptor instead.
func (*SetSpecialHoursResponse) Descriptor() ([]byte, []int) {
	return file_venue_venue_proto_rawDescGZIP(), []int{36}
}

func (x *SetSpecialHoursResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_venue_venue_proto protoreflect.FileDescriptor

const file_venue_venue_proto_rawDesc = "" +
	"\n" +
	"\x11venue/venue.proto\x12\x05venue\x1a\x13common/events.proto\"\x9f\x01\n" +
	"\x05Venue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x83\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xcf\x01\n" +
	"\x05Table\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\tcan_merge\x18\x05 \x01(\bR\bcanMerge\x12\x12\n" +
	"\x04zone\x18\x06 \x01(\tR\x04zone\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"N\n" +
	"\fOpeningHours\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12#\n" +
	"\x04days\x18\x02 \x03(\v2\x0f.venue.DayHoursR\x04days\"`\n" +
	"\bDayHours\x12\x18\n" +
	"\aweekday\x18\x01 \x01(\x05R\aweekday\x12\x1b\n" +
	"\topen_time\x18\x02 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x03 \x01(\tR\tcloseTime\"\x96\x01\n" +
	"\fSpecialHours\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\tR\tcloseTime\x12\x1b\n" +
	"\tis_closed\x18\x05 \x01(\bR\bisClosed\"^\n" +
	"\x12CreateVenueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"!\n" +
	"\x0fGetVenueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x11ListVenuesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"R\n" +
	"\x12UpdateVenueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"$\n" +
	"\x12DeleteVenueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x11CreateRoomRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\" \n" +
	"\x0eGetRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x10ListRoomsRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"7\n" +
	"\x11UpdateRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"#\n" +
	"\x11DeleteRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8e\x01\n" +
	"\x12CreateTableRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x1b\n" +
	"\tcan_merge\x18\x04 \x01(\bR\bcanMerge\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\"!\n" +
	"\x0fGetTableRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x11ListTablesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"h\n" +
	"\x12UpdateTableRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\"$\n" +
	"\x12DeleteTableRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x16SetOpeningHoursRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12#\n" +
	"\x04days\x18\x02 \x03(\v2\x0f.venue.DayHoursR\x04days\"3\n" +
	"\x16GetOpeningHoursRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\"\xa0\x01\n" +
	"\x16SetSpecialHoursRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\tR\tcloseTime\x12\x1b\n" +
	"\tis_closed\x18\x05 \x01(\bR\bisClosed\"v\n" +
	"\x18CheckAvailabilityRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12 \n" +
	"\x04slot\x18\x02 \x01(\v2\f.common.SlotR\x04slot\x12\x1d\n" +
	"\n" +
	"party_size\x18\x03 \x01(\x05R\tpartySize\"M\n" +
	"\x19CheckAvailabilityResponse\x120\n" +
	"\x06tables\x18\x01 \x03(\v2\x18.venue.TableAvailabilityR\x06tables\"\xaf\x01\n" +
	"\x11TableAvailability\x12&\n" +
	"\x05table\x18\x01 \x01(\v2\x10.common.TableRefR\x05table\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12<\n" +
	"\x11merged_with_table\x18\x04 \x01(\v2\x10.common.TableRefR\x0fmergedWithTable\"K\n" +
	"\x15GetTableLayoutRequest\x12\x19\n" +
	"\bvenue_id\x18\x01 \x01(\tR\avenueId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"W\n" +
	"\x16GetTableLayoutResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\x06tables\x18\x02 \x03(\v2\f.venue.TableR\x06tables\"P\n" +
	"\x12ListVenuesResponse\x12$\n" +
	"\x06venues\x18\x01 \x03(\v2\f.venue.VenueR\x06venues\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"L\n" +
	"\x11ListRoomsResponse\x12!\n" +
	"\x05rooms\x18\x01 \x03(\v2\v.venue.RoomR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"P\n" +
	"\x12ListTablesResponse\x12$\n" +
	"\x06tables\x18\x01 \x03(\v2\f.venue.TableR\x06tables\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"3\n" +
	"\x17SetOpeningHoursResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x13DeleteVenueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x12DeleteRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x13DeleteTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x17SetSpecialHoursResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x92\n" +
	"\n" +
	"\fVenueService\x126\n" +
	"\vCreateVenue\x12\x19.venue.CreateVenueRequest\x1a\f.venue.Venue\x120\n" +
	"\bGetVenue\x12\x16.venue.GetVenueRequest\x1a\f.venue.Venue\x12A\n" +
	"\n" +
	"ListVenues\x12\x18.venue.ListVenuesRequest\x1a\x19.venue.ListVenuesResponse\x126\n" +
	"\vUpdateVenue\x12\x19.venue.UpdateVenueRequest\x1a\f.venue.Venue\x12D\n" +
	"\vDeleteVenue\x12\x19.venue.DeleteVenueRequest\x1a\x1a.venue.DeleteVenueResponse\x123\n" +
	"\n" +
	"CreateRoom\x12\x18.venue.CreateRoomRequest\x1a\v.venue.Room\x12-\n" +
	"\aGetRoom\x12\x15.venue.GetRoomRequest\x1a\v.venue.Room\x12>\n" +
	"\tListRooms\x12\x17.venue.ListRoomsRequest\x1a\x18.venue.ListRoomsResponse\x123\n" +
	"\n" +
	"UpdateRoom\x12\x18.venue.UpdateRoomRequest\x1a\v.venue.Room\x12A\n" +
	"\n" +
	"DeleteRoom\x12\x18.venue.DeleteRoomRequest\x1a\x19.venue.DeleteRoomResponse\x126\n" +
	"\vCreateTable\x12\x19.venue.CreateTableRequest\x1a\f.venue.Table\x120\n" +
	"\bGetTable\x12\x16.venue.GetTableRequest\x1a\f.venue.Table\x12A\n" +
	"\n" +
	"ListTables\x12\x18.venue.ListTablesRequest\x1a\x19.venue.ListTablesResponse\x126\n" +
	"\vUpdateTable\x12\x19.venue.UpdateTableRequest\x1a\f.venue.Table\x12D\n" +
	"\vDeleteTable\x12\x19.venue.DeleteTableRequest\x1a\x1a.venue.DeleteTableResponse\x12P\n" +
	"\x0fSetOpeningHours\x12\x1d.venue.SetOpeningHoursRequest\x1a\x1e.venue.SetOpeningHoursResponse\x12E\n" +
	"\x0fGetOpeningHours\x12\x1d.venue.GetOpeningHoursRequest\x1a\x13.venue.OpeningHours\x12P\n" +
	"\x0fSetSpecialHours\x12\x1d.venue.SetSpecialHoursRequest\x1a\x1e.venue.SetSpecialHoursResponse\x12V\n" +
	"\x11CheckAvailability\x12\x1f.venue.CheckAvailabilityRequest\x1a .venue.CheckAvailabilityResponse\x12M\n" +
	"\x0eGetTableLayout\x12\x1c.venue.GetTableLayoutRequest\x1a\x1d.venue.GetTableLayoutResponseB\x18Z\x16booker/pkg/proto/venueb\x06proto3"

var (
	file_venue_venue_proto_rawDescOnce sync.Once
	file_venue_venue_proto_rawDescData []byte
)

func file_venue_venue_proto_rawDescGZIP() []byte {
	file_venue_venue_proto_rawDescOnce.Do(func() {
		file_venue_venue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_venue_venue_proto_rawDesc), len(file_venue_venue_proto_rawDesc)))
	})
	return file_venue_venue_proto_rawDescData
}

var file_venue_venue_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_venue_venue_proto_goTypes = []any{
	(*Venue)(nil),                     // 0: venue.Venue
	(*Room)(nil),                      // 1: venue.Room
	(*Table)(nil),                     // 2: venue.Table
	(*OpeningHours)(nil),              // 3: venue.OpeningHours
	(*DayHours)(nil),                  // 4: venue.DayHours
	(*SpecialHours)(nil),              // 5: venue.SpecialHours
	(*CreateVenueRequest)(nil),        // 6: venue.CreateVenueRequest
	(*GetVenueRequest)(nil),           // 7: venue.GetVenueRequest
	(*ListVenuesRequest)(nil),         // 8: venue.ListVenuesRequest
	(*UpdateVenueRequest)(nil),        // 9: venue.UpdateVenueRequest
	(*DeleteVenueRequest)(nil),        // 10: venue.DeleteVenueRequest
	(*CreateRoomRequest)(nil),         // 11: venue.CreateRoomRequest
	(*GetRoomRequest)(nil),            // 12: venue.GetRoomRequest
	(*ListRoomsRequest)(nil),          // 13: venue.ListRoomsRequest
	(*UpdateRoomRequest)(nil),         // 14: venue.UpdateRoomRequest
	(*DeleteRoomRequest)(nil),         // 15: venue.DeleteRoomRequest
	(*CreateTableRequest)(nil),        // 16: venue.CreateTableRequest
	(*GetTableRequest)(nil),           // 17: venue.GetTableRequest
	(*ListTablesRequest)(nil),         // 18: venue.ListTablesRequest
	(*UpdateTableRequest)(nil),        // 19: venue.UpdateTableRequest
	(*DeleteTableRequest)(nil),        // 20: venue.DeleteTableRequest
	(*SetOpeningHoursRequest)(nil),    // 21: venue.SetOpeningHoursRequest
	(*GetOpeningHoursRequest)(nil),    // 22: venue.GetOpeningHoursRequest
	(*SetSpecialHoursRequest)(nil),    // 23: venue.SetSpecialHoursRequest
	(*CheckAvailabilityRequest)(nil),  // 24: venue.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil), // 25: venue.CheckAvailabilityResponse
	(*TableAvailability)(nil),         // 26: venue.TableAvailability
	(*GetTableLayoutRequest)(nil),     // 27: venue.GetTableLayoutRequest
	(*GetTableLayoutResponse)(nil),    // 28: venue.GetTableLayoutResponse
	(*ListVenuesResponse)(nil),        // 29: venue.ListVenuesResponse
	(*ListRoomsResponse)(nil),         // 30: venue.ListRoomsResponse
	(*ListTablesResponse)(nil),        // 31: venue.ListTablesResponse
	(*SetOpeningHoursResponse)(nil),   // 32: venue.SetOpeningHoursResponse
	(*DeleteVenueResponse)(nil),       // 33: venue.DeleteVenueResponse
	(*DeleteRoomResponse)(nil),        // 34: venue.DeleteRoomResponse
	(*DeleteTableResponse)(nil),       // 35: venue.DeleteTableResponse
	(*SetSpecialHoursResponse)(nil),   // 36: venue.SetSpecialHoursResponse
	(*common.Slot)(nil),               // 37: common.Slot
	(*common.TableRef)(nil),           // 38: common.TableRef
}
var file_venue_venue_proto_depIdxs = []int32{
	4,  // 0: venue.OpeningHours.days:type_name -> venue.DayHours
	4,  // 1: venue.SetOpeningHoursRequest.days:type_name -> venue.DayHours
	37, // 2: venue.CheckAvailabilityRequest.slot:type_name -> common.Slot
	26, // 3: venue.CheckAvailabilityResponse.tables:type_name -> venue.TableAvailability
	38, // 4: venue.TableAvailability.table:type_name -> common.TableRef
	38, // 5: venue.TableAvailability.merged_with_table:type_name -> common.TableRef
	2,  // 6: venue.GetTableLayoutResponse.tables:type_name -> venue.Table
	0,  // 7: venue.ListVenuesResponse.venues:type_name -> venue.Venue
	1,  // 8: venue.ListRoomsResponse.rooms:type_name -> venue.Room
	2,  // 9: venue.ListTablesResponse.tables:type_name -> venue.Table
	6,  // 10: venue.VenueService.CreateVenue:input_type -> venue.CreateVenueRequest
	7,  // 11: venue.VenueService.GetVenue:input_type -> venue.GetVenueRequest
	8,  // 12: venue.VenueService.ListVenues:input_type -> venue.ListVenuesRequest
	9,  // 13: venue.VenueService.UpdateVenue:input_type -> venue.UpdateVenueRequest
	10, // 14: venue.VenueService.DeleteVenue:input_type -> venue.DeleteVenueRequest
	11, // 15: venue.VenueService.CreateRoom:input_type -> venue.CreateRoomRequest
	12, // 16: venue.VenueService.GetRoom:input_type -> venue.GetRoomRequest
	13, // 17: venue.VenueService.ListRooms:input_type -> venue.ListRoomsRequest
	14, // 18: venue.VenueService.UpdateRoom:input_type -> venue.UpdateRoomRequest
	15, // 19: venue.VenueService.DeleteRoom:input_type -> venue.DeleteRoomRequest
	16, // 20: venue.VenueService.CreateTable:input_type -> venue.CreateTableRequest
	17, // 21: venue.VenueService.GetTable:input_type -> venue.GetTableRequest
	18, // 22: venue.VenueService.ListTables:input_type -> venue.ListTablesRequest
	19, // 23: venue.VenueService.UpdateTable:input_type -> venue.UpdateTableRequest
	20, // 24: venue.VenueService.DeleteTable:input_type -> venue.DeleteTableRequest
	21, // 25: venue.VenueService.SetOpeningHours:input_type -> venue.SetOpeningHoursRequest
	22, // 26: venue.VenueService.GetOpeningHours:input_type -> venue.GetOpeningHoursRequest
	23, // 27: venue.VenueService.SetSpecialHours:input_type -> venue.SetSpecialHoursRequest
	24, // 28: venue.VenueService.CheckAvailability:input_type -> venue.CheckAvailabilityRequest
	27, // 29: venue.VenueService.GetTableLayout:input_type -> venue.GetTableLayoutRequest
	0,  // 30: venue.VenueService.CreateVenue:output_type -> venue.Venue
	0,  // 31: venue.VenueService.GetVenue:output_type -> venue.Venue
	29, // 32: venue.VenueService.ListVenues:output_type -> venue.ListVenuesResponse
	0,  // 33: venue.VenueService.UpdateVenue:output_type -> venue.Venue
	33, // 34: venue.VenueService.DeleteVenue:output_type -> venue.DeleteVenueResponse
	1,  // 35: venue.VenueService.CreateRoom:output_type -> venue.Room
	1,  // 36: venue.VenueService.GetRoom:output_type -> venue.Room
	30, // 37: venue.VenueService.ListRooms:output_type -> venue.ListRoomsResponse
	1,  // 38: venue.VenueService.UpdateRoom:output_type -> venue.Room
	34, // 39: venue.VenueService.DeleteRoom:output_type -> venue.DeleteRoomResponse
	2,  // 40: venue.VenueService.CreateTable:output_type -> venue.Table
	2,  // 41: venue.VenueService.GetTable:output_type -> venue.Table
	31, // 42: venue.VenueService.ListTables:output_type -> venue.ListTablesResponse
	2,  // 43: venue.VenueService.UpdateTable:output_type -> venue.Table
	35, // 44: venue.VenueService.DeleteTable:output_type -> venue.DeleteTableResponse
	32, // 45: venue.VenueService.SetOpeningHours:output_type -> venue.SetOpeningHoursResponse
	3,  // 46: venue.VenueService.GetOpeningHours:output_type -> venue.OpeningHours
	36, // 47: venue.VenueService.SetSpecialHours:output_type -> venue.SetSpecialHoursResponse
	25, // 48: venue.VenueService.CheckAvailability:output_type -> venue.CheckAvailabilityResponse
	28, // 49: venue.VenueService.GetTableLayout:output_type -> venue.GetTableLayoutResponse
	30, // [30:50] is the sub-list for method output_type
	10, // [10:30] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_venue_venue_proto_init() }
func file_venue_venue_proto_init() {
	if File_venue_venue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_venue_venue_proto_rawDesc), len(file_venue_venue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_venue_venue_proto_goTypes,
		DependencyIndexes: file_venue_venue_proto_depIdxs,
		MessageInfos:      file_venue_venue_proto_msgTypes,
	}.Build()
	File_venue_venue_proto = out.File
	file_venue_venue_proto_goTypes = nil
	file_venue_venue_proto_depIdxs = nil
}
