// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: venue/venue.proto

package venue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VenueService_CreateVenue_FullMethodName       = "/venue.VenueService/CreateVenue"
	VenueService_GetVenue_FullMethodName          = "/venue.VenueService/GetVenue"
	VenueService_ListVenues_FullMethodName        = "/venue.VenueService/ListVenues"
	VenueService_UpdateVenue_FullMethodName       = "/venue.VenueService/UpdateVenue"
	VenueService_DeleteVenue_FullMethodName       = "/venue.VenueService/DeleteVenue"
	VenueService_CreateRoom_FullMethodName        = "/venue.VenueService/CreateRoom"
	VenueService_GetRoom_FullMethodName           = "/venue.VenueService/GetRoom"
	VenueService_ListRooms_FullMethodName         = "/venue.VenueService/ListRooms"
	VenueService_UpdateRoom_FullMethodName        = "/venue.VenueService/UpdateRoom"
	VenueService_DeleteRoom_FullMethodName        = "/venue.VenueService/DeleteRoom"
	VenueService_CreateTable_FullMethodName       = "/venue.VenueService/CreateTable"
	VenueService_GetTable_FullMethodName          = "/venue.VenueService/GetTable"
	VenueService_ListTables_FullMethodName        = "/venue.VenueService/ListTables"
	VenueService_UpdateTable_FullMethodName       = "/venue.VenueService/UpdateTable"
	VenueService_DeleteTable_FullMethodName       = "/venue.VenueService/DeleteTable"
	VenueService_SetOpeningHours_FullMethodName   = "/venue.VenueService/SetOpeningHours"
	VenueService_GetOpeningHours_FullMethodName   = "/venue.VenueService/GetOpeningHours"
	VenueService_SetSpecialHours_FullMethodName   = "/venue.VenueService/SetSpecialHours"
	VenueService_CheckAvailability_FullMethodName = "/venue.VenueService/CheckAvailability"
	VenueService_GetTableLayout_FullMethodName    = "/venue.VenueService/GetTableLayout"
)

// VenueServiceClient is the client API for VenueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VenueServiceClient interface {
	// Заведения
	CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*Venue, error)
	GetVenue(ctx context.Context, in *GetVenueRequest, opts ...grpc.CallOption) (*Venue, error)
	ListVenues(ctx context.Context, in *ListVenuesRequest, opts ...grpc.CallOption) (*ListVenuesResponse, error)
	UpdateVenue(ctx context.Context, in *UpdateVenueRequest, opts ...grpc.CallOption) (*Venue, error)
	DeleteVenue(ctx context.Context, in *DeleteVenueRequest, opts ...grpc.CallOption) (*DeleteVenueResponse, error)
	// Залы
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
	ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
	UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error)
	DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*DeleteRoomResponse, error)
	// Столы
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*Table, error)
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*Table, error)
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	UpdateTable(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error)
	DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error)
	// Расписание
	SetOpeningHours(ctx context.Context, in *SetOpeningHoursRequest, opts ...grpc.CallOption) (*SetOpeningHoursResponse, error)
	GetOpeningHours(ctx context.Context, in *GetOpeningHoursRequest, opts ...grpc.CallOption) (*OpeningHours, error)
	SetSpecialHours(ctx context.Context, in *SetSpecialHoursRequest, opts ...grpc.CallOption) (*SetSpecialHoursResponse, error)
	// Доступность
	CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error)
	GetTableLayout(ctx context.Context, in *GetTableLayoutRequest, opts ...grpc.CallOption) (*GetTableLayoutResponse, error)
}

type venueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVenueServiceClient(cc grpc.ClientConnInterface) VenueServiceClient {
	return &venueServiceClient{cc}
}

func (c *venueServiceClient) CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*Venue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Venue)
	err := c.cc.Invoke(ctx, VenueService_CreateVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetVenue(ctx context.Context, in *GetVenueRequest, opts ...grpc.CallOption) (*Venue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Venue)
	err := c.cc.Invoke(ctx, VenueService_GetVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) ListVenues(ctx context.Context, in *ListVenuesRequest, opts ...grpc.CallOption) (*ListVenuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVenuesResponse)
	err := c.cc.Invoke(ctx, VenueService_ListVenues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) UpdateVenue(ctx context.Context, in *UpdateVenueRequest, opts ...grpc.CallOption) (*Venue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Venue)
	err := c.cc.Invoke(ctx, VenueService_UpdateVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) DeleteVenue(ctx context.Context, in *DeleteVenueRequest, opts ...grpc.CallOption) (*DeleteVenueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVenueResponse)
	err := c.cc.Invoke(ctx, VenueService_DeleteVenue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Room)
	err := c.cc.Invoke(ctx, VenueService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Room)
	err := c.cc.Invoke(ctx, VenueService_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomsResponse)
	err := c.cc.Invoke(ctx, VenueService_ListRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Room)
	err := c.cc.Invoke(ctx, VenueService_UpdateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*DeleteRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoomResponse)
	err := c.cc.Invoke(ctx, VenueService_DeleteRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Table)
	err := c.cc.Invoke(ctx, VenueService_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*Table, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Table)
	err := c.cc.Invoke(ctx, VenueService_GetTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, VenueService_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) UpdateTable(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Table)
	err := c.cc.Invoke(ctx, VenueService_UpdateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTableResponse)
	err := c.cc.Invoke(ctx, VenueService_DeleteTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) SetOpeningHours(ctx context.Context, in *SetOpeningHoursRequest, opts ...grpc.CallOption) (*SetOpeningHoursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOpeningHoursResponse)
	err := c.cc.Invoke(ctx, VenueService_SetOpeningHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetOpeningHours(ctx context.Context, in *GetOpeningHoursRequest, opts ...grpc.CallOption) (*OpeningHours, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpeningHours)
	err := c.cc.Invoke(ctx, VenueService_GetOpeningHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) SetSpecialHours(ctx context.Context, in *SetSpecialHoursRequest, opts ...grpc.CallOption) (*SetSpecialHoursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSpecialHoursResponse)
	err := c.cc.Invoke(ctx, VenueService_SetSpecialHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAvailabilityResponse)
	err := c.cc.Invoke(ctx, VenueService_CheckAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetTableLayout(ctx context.Context, in *GetTableLayoutRequest, opts ...grpc.CallOption) (*GetTableLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableLayoutResponse)
	err := c.cc.Invoke(ctx, VenueService_GetTableLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VenueServiceServer is the server API for VenueService service.
// All implementations must embed UnimplementedVenueServiceServer
// for forward compatibility.
type VenueServiceServer interface {
	// Заведения
	CreateVenue(context.Context, *CreateVenueRequest) (*Venue, error)
	GetVenue(context.Context, *GetVenueRequest) (*Venue, error)
	ListVenues(context.Context, *ListVenuesRequest) (*ListVenuesResponse, error)
	UpdateVenue(context.Context, *UpdateVenueRequest) (*Venue, error)
	DeleteVenue(context.Context, *DeleteVenueRequest) (*DeleteVenueResponse, error)
	// Залы
	CreateRoom(context.Context, *CreateRoomRequest) (*Room, error)
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
	UpdateRoom(context.Context, *UpdateRoomRequest) (*Room, error)
	DeleteRoom(context.Context, *DeleteRoomRequest) (*DeleteRoomResponse, error)
	// Столы
	CreateTable(context.Context, *CreateTableRequest) (*Table, error)
	GetTable(context.Context, *GetTableRequest) (*Table, error)
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	UpdateTable(context.Context, *UpdateTableRequest) (*Table, error)
	DeleteTable(context.Context, *DeleteTableRequest) (*DeleteTableResponse, error)
	// Расписание
	SetOpeningHours(context.Context, *SetOpeningHoursRequest) (*SetOpeningHoursResponse, error)
	GetOpeningHours(context.Context, *GetOpeningHoursRequest) (*OpeningHours, error)
	SetSpecialHours(context.Context, *SetSpecialHoursRequest) (*SetSpecialHoursResponse, error)
	// Доступность
	CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error)
	GetTableLayout(context.Context, *GetTableLayoutRequest) (*GetTableLayoutResponse, error)
	mustEmbedUnimplementedVenueServiceServer()
}

// UnimplementedVenueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVenueServiceServer struct{}

func (UnimplementedVenueServiceServer) CreateVenue(context.Context, *CreateVenueRequest) (*Venue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVenue not implemented")
}
func (UnimplementedVenueServiceServer) GetVenue(context.Context, *GetVenueRequest) (*Venue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVenue not implemented")
}
func (UnimplementedVenueServiceServer) ListVenues(context.Context, *ListVenuesRequest) (*ListVenuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVenues not implemented")
}
func (UnimplementedVenueServiceServer) UpdateVenue(context.Context, *UpdateVenueRequest) (*Venue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVenue not implemented")
}
func (UnimplementedVenueServiceServer) DeleteVenue(context.Context, *DeleteVenueRequest) (*DeleteVenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVenue not implemented")
}
func (UnimplementedVenueServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedVenueServiceServer) GetRoom(context.Context, *GetRoomRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedVenueServiceServer) ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRooms not implemented")
}
func (UnimplementedVenueServiceServer) UpdateRoom(context.Context, *UpdateRoomRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoom not implemented")
}
func (UnimplementedVenueServiceServer) DeleteRoom(context.Context, *DeleteRoomRequest) (*DeleteRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoom not implemented")
}
func (UnimplementedVenueServiceServer) CreateTable(context.Context, *CreateTableRequest) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedVenueServiceServer) GetTable(context.Context, *GetTableRequest) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTable not implemented")
}
func (UnimplementedVenueServiceServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedVenueServiceServer) UpdateTable(context.Context, *UpdateTableRequest) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTable not implemented")
}
func (UnimplementedVenueServiceServer) DeleteTable(context.Context, *DeleteTableRequest) (*DeleteTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTable not implemented")
}
func (UnimplementedVenueServiceServer) SetOpeningHours(context.Context, *SetOpeningHoursRequest) (*SetOpeningHoursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetOpeningHours not implemented")
}
func (UnimplementedVenueServiceServer) GetOpeningHours(context.Context, *GetOpeningHoursRequest) (*OpeningHours, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpeningHours not implemented")
}
func (UnimplementedVenueServiceServer) SetSpecialHours(context.Context, *SetSpecialHoursRequest) (*SetSpecialHoursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSpecialHours not implemented")
}
func (UnimplementedVenueServiceServer) CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAvailability not implemented")
}
func (UnimplementedVenueServiceServer) GetTableLayout(context.Context, *GetTableLayoutRequest) (*GetTableLayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableLayout not implemented")
}
func (UnimplementedVenueServiceServer) mustEmbedUnimplementedVenueServiceServer() {}
func (UnimplementedVenueServiceServer) testEmbeddedByValue()                      {}

// UnsafeVenueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VenueServiceServer will
// result in compilation errors.
type UnsafeVenueServiceServer interface {
	mustEmbedUnimplementedVenueServiceServer()
}

func RegisterVenueServiceServer(s grpc.ServiceRegistrar, srv VenueServiceServer) {
	// If the following call pancis, it indicates UnimplementedVenueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VenueService_ServiceDesc, srv)
}

func _VenueService_CreateVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).CreateVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_CreateVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).CreateVenue(ctx, req.(*CreateVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetVenue(ctx, req.(*GetVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_ListVenues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVenuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ListVenues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ListVenues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ListVenues(ctx, req.(*ListVenuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_UpdateVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).UpdateVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_UpdateVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).UpdateVenue(ctx, req.(*UpdateVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_DeleteVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).DeleteVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_DeleteVenue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).DeleteVenue(ctx, req.(*DeleteVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ListRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ListRooms(ctx, req.(*ListRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_UpdateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).UpdateRoom(ctx, req.(*UpdateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_DeleteRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).DeleteRoom(ctx, req.(*DeleteRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_UpdateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).UpdateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_UpdateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).UpdateTable(ctx, req.(*UpdateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_DeleteTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).DeleteTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_DeleteTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).DeleteTable(ctx, req.(*DeleteTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_SetOpeningHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOpeningHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).SetOpeningHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_SetOpeningHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).SetOpeningHours(ctx, req.(*SetOpeningHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetOpeningHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpeningHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetOpeningHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetOpeningHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetOpeningHours(ctx, req.(*GetOpeningHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_SetSpecialHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSpecialHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).SetSpecialHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_SetSpecialHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).SetSpecialHours(ctx, req.(*SetSpecialHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_CheckAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).CheckAvailability(ctx, req.(*CheckAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetTableLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetTableLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetTableLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetTableLayout(ctx, req.(*GetTableLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VenueService_ServiceDesc is the grpc.ServiceDesc for VenueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VenueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "venue.VenueService",
	HandlerType: (*VenueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVenue",
			Handler:    _VenueService_CreateVenue_Handler,
		},
		{
			MethodName: "GetVenue",
			Handler:    _VenueService_GetVenue_Handler,
		},
		{
			MethodName: "ListVenues",
			Handler:    _VenueService_ListVenues_Handler,
		},
		{
			MethodName: "UpdateVenue",
			Handler:    _VenueService_UpdateVenue_Handler,
		},
		{
			MethodName: "DeleteVenue",
			Handler:    _VenueService_DeleteVenue_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _VenueService_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _VenueService_GetRoom_Handler,
		},
		{
			MethodName: "ListRooms",
			Handler:    _VenueService_ListRooms_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _VenueService_UpdateRoom_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _VenueService_DeleteRoom_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _VenueService_CreateTable_Handler,
		},
		{
			MethodName: "GetTable",
			Handler:    _VenueService_GetTable_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _VenueService_ListTables_Handler,
		},
		{
			MethodName: "UpdateTable",
			Handler:    _VenueService_UpdateTable_Handler,
		},
		{
			MethodName: "DeleteTable",
			Handler:    _VenueService_DeleteTable_Handler,
		},
		{
			MethodName: "SetOpeningHours",
			Handler:    _VenueService_SetOpeningHours_Handler,
		},
		{
			MethodName: "GetOpeningHours",
			Handler:    _VenueService_GetOpeningHours_Handler,
		},
		{
			MethodName: "SetSpecialHours",
			Handler:    _VenueService_SetSpecialHours_Handler,
		},
		{
			MethodName: "CheckAvailability",
			Handler:    _VenueService_CheckAvailability_Handler,
		},
		{
			MethodName: "GetTableLayout",
			Handler:    _VenueService_GetTableLayout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "venue/venue.proto",
}
